app/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm, MyPasswordResetForm, MySetPasswordForm
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.models import User

app_name = "app"
# urls hado les urls marbotin b fnctn f view w dik fnct kima di (views.contact) hia li tjib page 
# html w had urls yretournii dik page b ism li raki baghyatah kima 'contact/'  'shop/'  'signup/'


urlpatterns = [
    path('', views.home, name='home'),
    path('about_us/', views.about_us, name='about_us'),
    path('delivery/', views.delivery, name='delivery'),
    path('privacy_policy/', views.privacy, name='privacy'),
    path('map/', views.map, name='map'),
    
    path('contact/', views.contact, name='contact'),
    path('shop-grid/', views.shop, name='shop'),
    path('signup/', views.CustomerRegistrationView.as_view(), name='signup'),
    # path('login/', views.loginuser, name='loginuser'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='app/login.html',
                                                         authentication_form=LoginForm), name='loginuser'),
    path('logout/', auth_views.LogoutView.as_view(next_page='app:loginuser'), name='logoutuser'),
    path('profile/', views.userprofile, name='userprofile'),
    path('category/<str:type>/', views.category, name='category'),
    path('search/', views.search, name='search')
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('blog/', views.blog, name='blog'),
    path('<int:blog_id>/', views.detail, name='detail'),
    path('category/<str:slug>', views.cat_blog, name='cat_blog'),
]

django_ogani_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from app.forms import MyPasswordResetForm, MySetPasswordForm
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='app/password_reset.html',
                                                                 form_class=MyPasswordResetForm),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='app/password_reset_confirm.html',
        form_class=MySetPasswordForm),
        name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='app/password_reset_complete.html'),
        name='password_reset_complete'),
        
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from audioop import maxpp
from distutils.command import upload
from email.mime import image
from unicodedata import category, name
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class  Category (models.Model):
  name = models.CharField(max_length=200,null=True,blank=True)

  def __str__(self):
        return self.name
    


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to="app/images/")
    published = models.DateField(auto_created=True,auto_now=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='categories',null=True,blank=True)
    slug = models.SlugField(blank=True,null=True)
    def save(self ,*args ,**kwargs):
        self.slug = slugify(self.title)
        super(Blog,self).save(*args,**kwargs)  
    def __str__(self):
        return self.title



class Comment (models.Model):  
    X = [
     ('Live','Live'),
     ('Stop','Stop'),
      ]      
    blog = models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='comments',null=True,blank=True)
    comment_name=models.CharField(max_length=30,null=True)
    comment_mail=models.CharField(max_length=30,null=True)
    comment_date = models.DateField(auto_created=True,auto_now=True)
    image=models.ImageField(upload_to="app/images/",null=True)
    comment = models.TextField(max_length=5000)
    status = models.CharField(max_length=50,choices=X,null=True,blank=True)
    
    def __str__(self):
       return self.comment_mail

blog/forms.py
from django import forms
from blog.models import Comment

class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'md-textarea form-control',
        'placeholder': 'comment here ...',
        'rows': '4',
    }))

    class Meta:
        model = Comment
        fields = ('content', )

blog/views.py
from contextlib import redirect_stderr
from django.shortcuts import render, get_object_or_404,redirect
from shop.models import Order
from .models import *
from app.views import home
from django.contrib import messages
# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator
from .filter import * 

@csrf_exempt
def detail(request, blog_id):
   
    comment_name = request.POST.get('comment_name')
    comment_mail = request.POST.get('comment_mail')
    comment = request.POST.get('comment')
    if request.method == 'POST':
            data_comment = Comment(comment_name=comment_name,comment_mail=comment_mail,
            comment=comment,blog=Blog.objects.get(pk=blog_id)) 
            data_comment.save()


    blog = get_object_or_404(Blog, pk=blog_id)
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.get_cart_items
    else:
        cartItems = 0




    context = {'blog': blog, 'cartItems': cartItems,
      'recents_blog': Blog.objects.order_by('-published')[0:3],
      'com':Comment.objects.all(),
      'c':Comment.objects.first(),
    }
    return render(request, 'blog/blog-details.html', context)


def blog(request):
    blogs = Blog.objects.all()

    ##filters by categorie
   
    paginator = Paginator(blogs, 4) 
    page = request.GET.get('page')
    blogs = paginator.get_page(page)

    if request.user.is_authenticated:#ida kan user authentifie
        customer = request.user.customer#cree customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)#order get create men customer
        cartItems = order.get_cart_items
    else:
        cartItems = 0
    


    categ=Category.objects.all()
    test = Blog.objects.all()

    context = {'blogs': blogs,'categ':categ,'recents_blog': Blog.objects.order_by('-published')[0:5],
    'ca':Category.objects.all(),'cartItems': cartItems,}

    return render(request, 'blog/blog.html', context)




def cat_blog(request,slug):
    category_blog = Blog.objects.filter(category=slug)
    
    product = get_object_or_404(Category, pk=slug)

    ca=Category.objects.all()
    context={'recents_blog': Blog.objects.order_by('-published')[0:5],
    'slug':category_blog,'ca':ca,
    'product':product,
    }
    return render(request, 'blog/cat_blog.html',context)
    

blog/templates/blog/blog-details.html
{% extends "app/base.html" %}

{% load static %}

{% block content %}


    <!-- Blog Details Hero Begin -->
    <section class="blog-details-hero set-bg" data-setbg="">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="blog__details__hero__text">
                        <h2>{{ blog.title }}</h2>
                        <ul>
                            <li>Admin</li>
                            <li>{{ blog.published|date:'F jS Y' }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Hero End -->

    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-5 order-md-1 order-2">
                    <div class="blog__sidebar">
                        
                        
                        <div class="blog__sidebar__item">
                            <h4>Recent Blog</h4>
                            {% for r in recents_blog %}
                            <ul>
                                <li><a href="{% url 'blog:detail' r.id %}">{{r.title}}</a></li>
                            </ul>
                            {% endfor %}
                        </div>
                     
                    </div>
                </div>
                <div class="col-lg-8 col-md-7 order-md-1 order-1">
                    <div class="blog__details__text">
                        <img src="{{ blog.image.url }}" alt="" width="500" height="400">
                        <p>{{ blog.description|safe }}</p>
                    </div>
                    <div class="blog__details__content">
                        <div class="row">
                            <div class="col-lg-6">
                            <h4>Comments</h4>
                            
                            <br>
                                <div class="blog__details__author">
                                    {% for c in com %}
                                    {% if c.status == 'Live'  %}
                                    <div class="blog__details__author__pic">
                                        <img src="{% static 'app/img/user.jpg' %}" height="25" width="25">
                                    </div>
                                    <div class="blog__details__author__text">
                                        <h6>{{c.comment_name}} </h6>
                                        <span>{{c.comment_date}}</span>
                                        <p>{{c.comment}}</p>
                                    </div>
                                    {% endif %}
                                    {% endfor %}
                                    
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="blog__details__widget">
                                    
                                    <div class="blog__details__social">
                                        <a target="_blank" href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                        <a href="#"><i class="fa fa-google-plus"></i></a>
                                        <a href="#"><i class="fa fa-linkedin"></i></a>
                                        <a href="#"><i class="fa fa-envelope"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

          <div class="contact-form spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="contact__form__title">
                        <h2>Leave comment</h2>
                    </div>
                </div>
            </div>
            {%  if request.user.is_authenticated  %}
            <form method='POST' >
				{% csrf_token %}
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <input type="text" name="comment_name" placeholder="Your name">
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <input type="text" name="comment_mail" placeholder="Your Email">
                    </div>
                    <div class="col-lg-12 text-center">
                        <textarea name="comment" placeholder="Your comment"></textarea>
                        <button type="submit" value="Submit" class="site-btn">Leave Comment</button>
                    </div>
                </div>
            </form>
            {% endif %}
        </div>
    </div>
    </section>
    <!-- Blog Details Section End -->

    <!-- Related Blog Section Begin -->
  
    <!-- Related Blog Section End -->

{% endblock %}

blog/templates/blog/blog.html
{% extends "app/base.html" %}

{% load static %}

{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Blog</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url 'app:home' %}">Home</a>
                            <a>Blog</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Blog Section Begin -->
    <section class="blog spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-5">
                    <div class="blog__sidebar">
                      
                        <div class="blog__sidebar__item">
                            <h4>Categories</h4>
                            {% for cat in categ %}
                            <ul>
                                <li><a href="{% url 'blog:cat_blog' cat.id %}">{{cat.name}}</a></li>
                            </ul>
                            {% endfor %}
                        </div>
                        <div class="blog__sidebar__item">
                            <h4>Recent News</h4>
                            <div class="blog__sidebar__recent">
                            {% for r in recents_blog %}
                                <a  class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="{{r.image.url}}" height='30px' width='40px' alt="">
                                    </div>
                                   <a href="{% url 'blog:detail' r.id %}" >
                                    <div class="blog__sidebar__recent__item__text" >
                                        <h6 > {{r.title}}</h6>
                                        <span>{{r.published}}</span>
                                    </div> </a>
                                </a>
                               
                               {% endfor %}

                            </div>
                        </div>
                        <div class="blog__sidebar__item">
                            <h4>Search By</h4>
                            <div class="blog__sidebar__item__tags">
                                {% for cat in ca %}
                                <a href="{% url 'blog:cat_blog' cat.id %}">{{cat.name}}</a>
                                 {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>


                <div class="col-lg-8 col-md-7">
                    <div class="row">
                        {% for blog in blogs %}
                        <div class="col-lg-6 col-md-6 col-sm-6">

                            <div class="blog__item">
                                <div class="blog__item__pic">
                                    <img src="{{ blog.image.url }}" alt="">
                                </div>
                                <div class="blog__item__text">
                                    <ul>
                                        <li><i class="fa fa-calendar-o"></i> {{ blog.published|date:'F jS Y' }}</li>
                                    </ul>
                                    <h5><a href="{% url 'blog:detail' blog.id %}" >{{ blog.title }}</a></h5>
                                    <p>{{ blog.description|striptags|truncatechars:100}}  </p>
                                    <a href="{% url 'blog:detail' blog.id %}" class="blog__btn">READ MORE <span class="arrow_right"></span></a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="col-lg-12">
                            
                                		{% if blogs.has_other_pages %}
					<!--Pagination-->
					<nav class="d-flex justify-content-center wow fadeIn">
						<ul class="pagination pg-blue">

						{% if blogs.has_previous %}
							<!--Arrow left-->
							<li class="page-item ">
							<a class="page-link" href="?page={{blogs.previous_page_number}}" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
								<span class="sr-only">Previous</span>
							</a>
							</li>
						{% else %}
							<li class="page-item disabled"></li>
						{% endif %}

						{% for pages in blogs.paginator.page_range %}
							{% if blogs.number == pages %}
							<li class="page-item ">
								<a class="page-link" href="#">{{pages}}</a>
							</li>
							{% else %}
							<li class="page-item"><a class="page-link current" href="?page={{pages}}">{{pages}}</a></li>
							{% endif %}    
						{% endfor %}

						{% if blogs.has_next %}
							<li class="page-item">
							<a class="page-link" href="?page={{blogs.next_page_number}}" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
								<span class="sr-only">Next</span>
							</a>
							</li>
							{% else %}
							<li class="page-item disabled"></li>
						{% endif %}
						</ul>
					</nav>
					<!--Pagination-->
					{% endif %}

                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </section>
    <!-- Blog Section End -->


{% endblock %}

blog/templates/blog/cat_blog.html
{% extends "app/base.html" %}

{% load static %}

{% block content %}
 <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Categories Blog</h2>
                         <div class="breadcrumb__text">
                        <h2>{{product.name}}</h2>
                        <div class="breadcrumb__option">
                            
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->




        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-5">
                    <div class="blog__sidebar">
                        
                        <div class="blog__sidebar__item">
                            <h4>Categories</h4>
                            {% for cat in ca %}
                            <ul>
                                <li><a href="{% url 'blog:cat_blog' cat.id %}">{{cat.name}}</a></li>
                            </ul>
                            {% endfor %}
                        </div>
                        <div class="blog__sidebar__item">
                            <h4>Recent Blog</h4>
                            <div class="blog__sidebar__recent">
                            {% for r in recents_blog %}
                                <a  class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="{{r.image.url}}" height='30px' width='40px' alt="">
                                    </div>
                                   <a href="{% url 'blog:detail' r.id %}" >
                                    <div class="blog__sidebar__recent__item__text" >
                                        <h6 > {{r.title}}</h6>
                                        <span>{{r.published}}</span>
                                    </div> </a>
                                </a>
                               
                               {% endfor %}

                            </div>
                        </div>
                       
                       

                    </div>
                </div>
            
<div class="col-lg-8 col-md-7">
                    <div class="row">
                      
        {% for s in slug %}

                        <div class="col-lg-6 col-md-6 col-sm-6">

                            <div class="blog__item">
                                <div class="blog__item__pic">
                                    <img src="{{ s.image.url }}" alt="">
                                </div>
                                <div class="blog__item__text">
                                    <ul>
                                        <li><i class="fa fa-calendar-o"></i> {{ s.published|date:'F jS Y' }}</li>
                                    </ul>
                                    <h5><a href="{% url 'blog:detail' s.id %}" >{{ s.title }}</a></h5>
                                    <p>{{ s.description|striptags|truncatechars:100}}  </p>
                                    <a href="{% url 'blog:detail' s.id %}" class="blog__btn">READ MORE <span class="arrow_right"></span></a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

       </div>
        </div>
        </div>
        </div>
    </section>
    <!-- Blog Section End -->
{% endblock %}