app/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm, MyPasswordResetForm, MySetPasswordForm
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.models import User

app_name = "app"
# urls hado les urls marbotin b fnctn f view w dik fnct kima di (views.contact) hia li tjib page 
# html w had urls yretournii dik page b ism li raki baghyatah kima 'contact/'  'shop/'  'signup/'


urlpatterns = [
    path('', views.home, name='home'),
    path('about_us/', views.about_us, name='about_us'),
    path('delivery/', views.delivery, name='delivery'),
    path('privacy_policy/', views.privacy, name='privacy'),
    path('map/', views.map, name='map'),
    
    path('contact/', views.contact, name='contact'),
    path('shop-grid/', views.shop, name='shop'),
    path('signup/', views.CustomerRegistrationView.as_view(), name='signup'),
    # path('login/', views.loginuser, name='loginuser'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='app/login.html',
                                                         authentication_form=LoginForm), name='loginuser'),
    path('logout/', auth_views.LogoutView.as_view(next_page='app:loginuser'), name='logoutuser'),
    path('profile/', views.userprofile, name='userprofile'),
    path('category/<str:type>/', views.category, name='category'),
    path('search/', views.search, name='search')
]

django_ogani_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from app.forms import MyPasswordResetForm, MySetPasswordForm
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='app/password_reset.html',
                                                                 form_class=MyPasswordResetForm),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='app/password_reset_confirm.html',
        form_class=MySetPasswordForm),
        name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='app/password_reset_complete.html'),
        name='password_reset_complete'),
        
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path('productinfo/<int:product_id>/', views.productinfo, name='productinfo'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateitem, name='update_item'),
    path('process_order/', views.process_order, name='process_order'),

]

shop/models.py
from statistics import mode
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

CATEGORY_CHOICES = (
    ('FL', 'Farine_Semoul'),
    ('P', 'Pates'),
    ('G', 'Gateaux'),
    ('S', 'Sucrerie'),
    ('OF', 'Graines'),
    ('L', 'Laitiers'),
    ('B', 'Boisson'),
    ('PFM', 'Produit_Fait_Maison'),
   
    ('CM', 'Compliment Alimentaire'),
)

FEATURED_CATEGORY_CHOICES = (
    
    ('FL', 'Farine_Semoul'),
    ('P', 'Pates'),
    ('G', 'Gateaux'),
    ('S', 'Sucrerie'),
    ('OF', 'Graines'),
    ('L', 'Laitiers'),
    ('B', 'Boisson'),
    ('PFM', 'Produit_Fait_Maison'),
   
    ('CM', 'Compliment_Alimentaire'),
)

CATEGORY_CHOICES_MAP = {
    'Farine_Semoul': 'FL',
    'Pates': 'P',
    'Gateaux': 'G',
    'Sucrerie': 'S',
    'Graines': 'OF',
    'Laitiers': 'L',
    'Boisson': 'B',
    'Produit_Fait_Maison': 'PFM',
  
    'Compliment_Alimentaire': 'CM',
}

class Product(models.Model):
    test={('available','available'),
       ('sold','sold')  }
    title = models.CharField(max_length=200)

    image1 = models.ImageField(upload_to="app/images/")
    image2 = models.ImageField(upload_to="app/images/", null=True, blank=True)
    image3 = models.ImageField(upload_to="app/images/", null=True, blank=True)
    image4 = models.ImageField(upload_to="app/images/", null=True, blank=True)
    image5 = models.ImageField(upload_to="app/images/", null=True, blank=True)

    shortinfo = models.TextField(default='NA')
    description = models.TextField(default='NA')
    weight = models.CharField(blank=True,null=True, max_length=10)
    price = models.FloatField()
    discounted_price = models.FloatField(null=True, blank=True)
    fav_count = models.IntegerField(null=True, blank=True)
    latest = models.DateField()
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=3)
    quantity1= models.CharField(choices=test,max_length=10,default='available') 

    def __str__(self):
        return self.title
        


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name = 'customer' ,null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.name)


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)
    
    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        total_with_shipping = total + 200.0
        dinars_total= total_with_shipping/145.632
        return total, total_with_shipping,dinars_total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

  


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        if self.product.discounted_price is not None:
            total = (self.product.price - self.product.discounted_price) * self.quantity
        else:
            total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, blank=True, null=True)
    country = models.CharField(max_length=20)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=20)
    postal_code = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=17)

    def __str__(self):
        return str(self.address)

shop/views.py
import datetime
from itertools import product
import json
from django.contrib.auth.decorators import login_required
from django.core.mail.backends import console
from django.db.models import Q
from django.http import JsonResponse
from app.forms import *
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from shop.models import *
from . import utils
from .utils import *


def productinfo(request, product_id):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.get_cart_items
    else:
        order = {'get_cart_total': (0, 70)}
        cartItems = 0
    
    product = get_object_or_404(Product, pk=product_id)
    products = Product.objects.filter(category=product.category).exclude(pk=product_id)
    context = {'order': order, 'cartItems': cartItems, 'product': product, 'products': products,}
    return render(request, 'shop/shop-details.html', context)

@login_required
def cart(request):

    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    test = User.objects.filter(city= ProfileEditForm.cleaned_data['sidi bel abbes']).exists()
    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'shop/shopping-cart.html', context)

@login_required
def checkout(request):
    print('Checkout...')
    data = cartData(request, in_check_out=True)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    customer = data['customer']
    shipping_address = data['shipping_address']
    context = {'items': items, 'order': order, 'shipping_address': shipping_address,
               'customer': customer, 'cartItems': cartItems}

    return render(request, 'shop/checkout.html', context)


@login_required
def updateitem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action: ', action, 'Product: ', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderitem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderitem.quantity = orderitem.quantity + 1
    elif action == 'remove':
        orderitem.quantity = orderitem.quantity - 1
    orderitem.save()

    if orderitem.quantity == 0:
        orderitem.delete()

    return JsonResponse('Item was added', safe=False)

@login_required
def process_order(request):
    print('process order start...')
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    print('Data: ', data)
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)

    else:
        print('user not logged in')
        customer, order = guestOrder(request, data)
        print('Customer: ',customer,' order: ', order)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total[1]:
        order.complete = True
    order.save()
    print('process order end...')
    return JsonResponse('payment complete', safe=False)

shop/templates/shop/checkout.html
{% extends "app/base.html" %}

{% load static %}

{% block content %}

  

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg=" ">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Checkout</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url 'app:home' %}">Home</a>
                            <span>Checkout</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Checkout Section Begin -->
    <section class="checkout spad">
        <div class="container">
            <div class="checkout__form">
                <h4>Billing Details</h4>
                <form action="" id="form" method="post" onsubmit="return false">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-8 col-md-6">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Fist Name<span>*</span></p>
                                        <input type="text" value="{{ customer.user.first_name }}" name="first_name">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Last Name<span>*</span></p>
                                        <input type="text" value="{{ customer.user.last_name }}" name="last_name">
                                    </div>
                                </div>
                            </div>
                            <div class="checkout__input">
                                <p>Country<span>*</span></p>
                                <input type="text" value="{{ shipping_address.country }}" name="country">
                            </div>
                            <div class="checkout__input">
                                <p>Address<span>*</span></p>
                                <input type="text" value="{{ shipping_address.address }}" class="checkout__input__add" name="address">
                            </div>
                            <div class="checkout__input">
                                <p>City<span>*</span></p>
                                <input type="text"  value="{{ shipping_address.city }}" name="city">
                            </div>
                            <div class="checkout__input">
                                <p>Postcode / ZIP<span>*</span></p>
                                <input type="text" value="{{ shipping_address.postal_code }}" name="postal_code">
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Phone<span>*</span></p>
                                        <input type="text"  value="{{ shipping_address.phone_number }}" name="phone_number">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Email<span>*</span></p>
                                        <input type="text" value="{{ customer.email }}" name="email">
                                    </div>
                                </div>
                            </div>
                        </div>
    <style>
   @media print {

       body{visibility : hidden ;}
       .print{visibility : visible ;}
   }

                </style>
                        <div class="col-lg-4 col-md-6">
                            <div class="checkout__order print">
                                <h4>Your Order</h4>
                                <div class="checkout__order__products">Products <span>Total</span></div>
                                {% for item in items %}
                                <ul>
                                    <li >{{ item.product.title }} <span>{{ item.get_total }}dz</span></li>
                                </ul>
                                {% endfor %}
                                <div class="checkout__order__subtotal">Subtotal <span>{{ order.get_cart_total.0|floatformat:2 }} dz</span></div>
                                <div class="checkout__order__shipping">Shipping <span>200 dz</span></div>
                                <div class="checkout__order__total">Total <span>{{ order.get_cart_total.1|floatformat:2 }} dz</span></div>

                                <div id="paypal-button-container"></div>

                                {% if order.get_cart_total.0 == 0 %}
                                <button type="submit" class="site-btn" value="Click"onclick="proceedcart();">PLACE ORDER</button>
                                <span class="text-danger">you can't proceed out your cart is empty <a  href="{% url 'app:shop' %}" >let's shopping again</a></span>
                                {% else %}
                                <button type="submit" class="site-btn" id="make-payment">PLACE ORDER</button>
                                <span class="text-body">confirm your order</span>
                                {% endif %}
                                

                            </div>
                            
                        <br>
                        <button onclick="window.print();return false;"  class="site-btn">PRINT ORDER</button><br>
                         <a class="text-body">you can print your total</a><br><br><br>
                         <a class="text-body">delivry with allo jibli</a>&nbsp;&nbsp; <a target="_blank" href="http://allojibli.dz/"><img src="{% static 'app/img/hero/allo_jibli.jpg' %}"  height="35"  widht="35"></a>
                        </div>
                        
                    </div>
                    
                </form>
            </div>
        </div>
    </section>
    <!-- Checkout Section End -->


<script src="https://www.paypal.com/sdk/js?client-id=ATXD5OJTk7RgieWTtW4rl3nCdoLGPY2h_Kyt6cu9YHBebid3_-UgaQzQXhGRnyDF7-BC-__rQcOGGYAO&currency=USD&disable-funding=credit"></script>

<script type="text/javascript">
    var total = '{{ order.get_cart_total.2}}'

    var form = document.getElementById('form')



    document.getElementById('make-payment').addEventListener('click',function(e){

        console.log('clicked')
        document.getElementById('make-payment').style.visibility='hidden'
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: parseFloat(total).toFixed(2)
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(orderData) {
                    // Successful capture! For demo purposes:
                    console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                    submitFormData()
                    // Replace the above to show a success message within this page, e.g.
                    // const element = document.getElementById('paypal-button-container');
                    // element.innerHTML = '';
                    // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                    // Or go to another URL:  actions.redirect('thank_you.html');
                });
            }


        }).render('#paypal-button-container');
    })
    function submitFormData(){
        console.log('Payment button clicked')
        var userFormData = {
            'name': form.first_name.value+' '+form.last_name.value,
            'email': form.email.value,
            'total':total,
        }
        var shippingInfo = {
            'address': form.address.value,
            'city':form.city.value ,
            'country': form.country.value,
            'postal_code': form.postal_code.value,
            'phone_number': form.phone_number.value ,
        }
        var url = 'http://127.0.0.1:8000/shop/process_order/'
        fetch(url,{
            method:'POST',
            headers:{
                'Content-Type':'application/json',
                'X-CSRFToken':csrftoken,
            },
            body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo})
        })
        .then((response) => response.json())
        .then((data) => {
            console.log('Success: ',data);
            alert('Transaction completed , it will be delivered on 2 days THANK YOU');

            cart = {}
            document.cookie = 'cart='+ JSON.stringify(cart) + ";domain=;path=/"


            window.location.replace("{% url 'app:shop' %}");
        })
        .catch(err => console.log(err));
    }
</script>
    <script type="text/javascript">
function proceedcart() {
alert ("sorry your cart it's empty");
}

</script>

{% endblock %}

shop/templates/shop/shopping-cart.html
{% extends "app/base.html" %}

{% load static %}
{% load mathfilters %}

{% block content %}
   

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Shopping Cart</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url 'app:home' %}">Home</a>
                            <a>Shopping Cart</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shoping Cart Section Begin -->
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th class="shoping__product">Products</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in items %}
                                <tr>
                                    <td class="shoping__cart__item">
                                        <img src="{{ item.product.image1.url }}" alt="" height="200" width="200">
                                        <h5>{{ item.product.title }}</h5>
                                    </td>
                                    <td class="shoping__cart__price">
                                        {% if item.product.discounted_price is not none %}
                                        {{ item.product.price|sub:item.product.discounted_price }}dz
                                        {% else %}
                                        {{ item.product.price }}dz
                                        {% endif %}
                                    </td>
                                    <td class="shoping__cart__quantity">
                                        <div class="quantity">
                                            <div class="pro-qty" style="text-align: center;">
                                                <span class="dec qtybtn update-cart" data-product="{{ item.product.id }}" data-action="remove">-</span>
                                                <input type="text" value="{{ item.quantity }}">
                                                <span class="inc qtybtn update-cart" data-product="{{ item.product.id }}" data-action="add">+</span>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="shoping__cart__total">
                                        {{ item.get_total }}
                                    </td>
                                   
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__btns">
                        <a href="{% url 'app:shop' %}" class="primary-btn cart-btn">CONTINUE SHOPPING</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="shoping__continue">

                    </div>
                </div>
                
            
                
                <div class="col-lg-6 " >
                    <div class="shoping__checkout print">
                    <img src="{% static 'app/img/lolo1.png' %}" alt=""  height="50" width="50"></a>
                        <h5 style="text-align:center;">Cart Total</h5>
                        
                        <ul>
                            <li>Subtotal <span>{{ order.get_cart_total.0|floatformat:2 }} dz</span></li>
                            <li>Shipping <span>200 dz</span></li>
                            <li>Total <span>{{ order.get_cart_total.1|floatformat:2 }} dz</span></li>
                        </ul>
                        {% if order.get_cart_total.0 == 0 %}
                        <a href="#" class="primary-btn " value="Click"onclick="proceedcart();">PROCEED TO CHECKOUT</a>
                        <span class="text-danger">you can't proceed out your cart is empty <a  href="{% url 'app:shop' %}" >let's shopping</a></span>
                        {% else %}
                        <a href="{% url 'shop:checkout' %}" class="primary-btn">PROCEED TO CHECKOUT</a>
                        {% endif %}

                    </div>
                    
                        
                </div>


                
            </div>
        </div>
    </section>
    <!-- Shoping Cart Section End -->
    <script type="text/javascript">
function proceedcart() {
alert ("sorry your cart is empty");
}

</script>


{% endblock %}