app/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm, MyPasswordResetForm, MySetPasswordForm
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.models import User

app_name = "app"
# urls hado les urls marbotin b fnctn f view w dik fnct kima di (views.contact) hia li tjib page 
# html w had urls yretournii dik page b ism li raki baghyatah kima 'contact/'  'shop/'  'signup/'


urlpatterns = [
    path('', views.home, name='home'),
    path('about_us/', views.about_us, name='about_us'),
    path('delivery/', views.delivery, name='delivery'),
    path('privacy_policy/', views.privacy, name='privacy'),
    path('map/', views.map, name='map'),
    
    path('contact/', views.contact, name='contact'),
    path('shop-grid/', views.shop, name='shop'),
    path('signup/', views.CustomerRegistrationView.as_view(), name='signup'),
    # path('login/', views.loginuser, name='loginuser'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='app/login.html',
                                                         authentication_form=LoginForm), name='loginuser'),
    path('logout/', auth_views.LogoutView.as_view(next_page='app:loginuser'), name='logoutuser'),
    path('profile/', views.userprofile, name='userprofile'),
    path('category/<str:type>/', views.category, name='category'),
    path('search/', views.search, name='search')
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('blog/', views.blog, name='blog'),
    path('<int:blog_id>/', views.detail, name='detail'),
    path('category/<str:slug>', views.cat_blog, name='cat_blog'),
]

django_ogani_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from app.forms import MyPasswordResetForm, MySetPasswordForm
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='app/password_reset.html',
                                                                 form_class=MyPasswordResetForm),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='app/password_reset_confirm.html',
        form_class=MySetPasswordForm),
        name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='app/password_reset_complete.html'),
        name='password_reset_complete'),
        
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path('productinfo/<int:product_id>/', views.productinfo, name='productinfo'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateitem, name='update_item'),
    path('process_order/', views.process_order, name='process_order'),

]

app/templates/app/contact.html
{% extends "app/base.html" %}

{% load static %}

{% block content %}

    

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Contact Us</h2>
                        <div class="breadcrumb__option">
                            <a href="./index.html">Home</a>
                            </a>Contact Us</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Contact Section Begin -->
    <section class="contact spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_phone"></span>
                        <h4>Phone</h4>
                        <p>+{{cont.phone}}</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_pin_alt"></span>
                        <h4>Address</h4>
                        <p>{{cont.adress}}</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_clock_alt"></span>
                        <h4>Open time</h4>
                        <p>from saturday to thursday<br>
                          at 9h to 21h 30</p>
                        
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_mail_alt"></span>
                        <h4>Email</h4>
                        <p>{{cont.emaill}}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->

    <!-- Map Begin -->
    <div class="map">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d407.55076465381296!2d-0.6236644087397453!3d35.19635182856276!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd7f01b9736594cf%3A0xd970eae78a8df58b!2sLolo%20Nutrition!5e0!3m2!1sfr!2sdz!4v1653739324583!5m2!1sfr!2sdz" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        <div class="map-inside">
            
            <div class="inside-widget">
                <h4>sidi bel abbes</h4>
                <ul>
                    <li>Phone: +213 6666666</li>
                    <li>Lolo Nutrition  Rue des fréres Chaabane, Sidi Bel Abbès</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Map End -->

    <!-- Contact Form Begin -->
    <div class="contact-form spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="contact__form__title">
                        <h2>Leave Message</h2>
                    </div>
                </div>
            </div>
                                        <form method="POST" >
                       <!-- method post pour envoyer des données sensible -->                   
                                        {% csrf_token %}
                                            <div class="row">
                                                <div class="col-lg-6 col-md-6">
                                                    <input type="text" name="subject" placeholder="Your name" required="required">
                                                </div>

                                                <div class="col-lg-6 col-md-6">
                                                    <input type="email" name="email" placeholder="Your Email" required="required">
                                                </div>

                                                <div class="col-lg-12 text-center">
                                                    <textarea name="message" placeholder="Your message" required="required"></textarea>
                                                    <button type="submit" class="site-btn">SEND MESSAGE</button>
                                                </div>
                                                
                                            </div>
                                        </form>
        </div>
    </div>
    <!-- Contact Form End -->
{% endblock %}

app/templates/app/emptycart.html
{% extends "app/base.html" %}

{% load static %}

{% block content %}



    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'app/img/ban_lo.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Cart</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->
    <br><br>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h4 class="text-center">No product in your cart!</h4><br>
            <div class="text-center">
                <img src="{% static 'app/img/cart/emptycartimage.jpg' %}" alt=""
                     class="img-fluid img-thumbnail w-25">
            </div>
        </div>
    </div>

    <br><br>
    <br><br>
    <!-- Checkout Section End -->
{% endblock %}

app/templates/app/index.html
{% extends "app/base.html" %}

{% load static %}
{% load i18n %}
{% trans 'Lorem ipsum ...' %}

{% block content %}
    <!-- Hero Section Begin -->
    <section class="hero">
        <div class="container">
            <div class="row">
                
                <div class="col-lg-9">
                   
                    <div class="hero__item set-bg" data-setbg="{% static 'app/img/banner.jpg' %}">
                        <div class="hero__text">
                            <span>FRUIT FRESH</span>
                            <h2>Free Gluten <br />100% Healthy</h2>
                            <p>Delivery Available</p>
                            <a href="{% url 'app:shop'%}" class="primary-btn">SHOP NOW</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Categories Section Begin -->
   
    <!-- Categories Section End -->

    <!-- Featured Section Begin -->
    <section class="featured spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>Featured Product</h2>
                    </div>
                    <div class="featured__controls">
                        <ul>
                            <li class="active" data-filter="*"><img src="{% static 'app/icon/all.png' %}" width="40" height="40" ><br>all</li>
                            <li data-filter=".Pates"><img src="{% static 'app/icon/Pates.png' %}" width="40" height="40" ><br>Pasta</li>
                            <li data-filter=".Laitiers"><img src="{% static 'app/icon/les-produits-laitiers.png' %}" width="40" height="40" ><br>Dairymen</li>
                            <li data-filter=".Boissons"><img src="{% static 'app/icon/boisson.png' %}" width="40" height="40" ><br>Beverage</li>
                            <li data-filter=".Produit_Fait_Maison"><img src="{% static 'app/icon/produitsfaitmaison.png' %}" width="40" height="40" ><br>Homemade</li>
                            <li data-filter=".Farine_Semoul"><img src="{% static 'app/icon/Farine.png' %}" width="40" height="40" ><br>Semolina flour</li>
                            <li data-filter=".Gateaux"><img src="{% static 'app/icon/Gateaux.png' %}" width="40" height="40" ><br>Cakes</li>
                            <li data-filter=".Sucrerie"><img src="{% static 'app/icon/des-sucreries.png' %}" width="40" height="40" ><br>Sugar factory</li>
                            <li data-filter=".Graines"><img src="{% static 'app/icon/Graines.png' %}" width="40" height="40" ><br>Seeds</li>
                            <li data-filter=".Compliment_Alimentaire"><img src="{% static 'app/icon/complement-alimentaire.png' %}" width="40" height="40" ><br>supplements</li>
                           
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row featured__filter">
                {% for item in featured_N_products %}
                    <div class="col-lg-3 col-md-4 col-sm-6 mix {{ item.category }} {{ item.category }}">
                        <div class="featured__item">
                            <div class="featured__item__pic set-bg" data-setbg="{{ item.image }}">
                                
                            </div>
                            <div class="featured__item__text">
                                <h3><a href="{% url 'shop:productinfo' item.product_id %}">{{ item.title }}</a></h3>
                                <h5>{{ item.price }}dz</h5>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Featured Section End -->

    <!-- Banner Begin -->
    <div class="banner">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="banner__pic">
                        <img src="{% static 'app/img/banner/banner-1.jpg' %}" alt="">
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="banner__pic">
                        <img src="{% static 'app/img/banner/banner-2.jpg' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Banner End -->

    <!-- Latest Product Section Begin -->
    <section class="latest-product spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="latest-product__text">
                        <h4>Latest Products</h4>
                        <div class="latest-product__slider owl-carousel">
                            {% for chunk in latest_N_Products %}

                                <div class="latest-prdouct__slider__item">
                                    {% for item in chunk %}
                                        <a href="{% url 'shop:productinfo' item.product_id %}" class="latest-product__item">
                                            <div class="latest-product__item__pic">
                                                <img src="{{ item.image }}" alt="">
                                            </div>
                                            <div class="latest-product__item__text">
                                                <h6>{{ item.title }}</h6>
                                                <span>{{ item.price }}dz</span>
                                            </div>
                                        </a>
                                    {% endfor %}
                                </div>

                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="latest-product__text">
                        <h4>Top Rated Products</h4>
                        <div class="latest-product__slider owl-carousel">
                            {% for chunk in favourite_N_Products %}
                                <div class="latest-prdouct__slider__item">
                                    {% for item in chunk %}
                                        <a href="{% url 'shop:productinfo' item.product_id %}" class="latest-product__item">
                                            <div class="latest-product__item__pic">
                                                <img src="{{ item.image }}" alt="">
                                            </div>
                                            <div class="latest-product__item__text">
                                                <h6>{{ item.title }}</h6>
                                                <span>{{ item.price }} dz</span>
                                            </div>
                                        </a>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Latest Product Section End -->

    <!-- Blog Section Begin -->
    <section class="from-blog spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title from-blog__title">
                        <h2>From The Blog</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for blog in blogs %}
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <div class="blog__item">
                        <div class="blog__item__pic">
                            <img src="{{ blog.image.url }}" alt="">
                        </div>
                        <div class="blog__item__text">
                            <ul>
                                <li><i class="fa fa-calendar-o"></i> {{ blog.published|date:'F jS Y' }}</li>
                            </ul>
                            <h5><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a></h5>
                            <p>{{ blog.description|striptags|truncatechars:250}} </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
         {% if blogs.has_other_pages %}
					<!--Pagination-->
					<nav class="d-flex justify-content-center wow fadeIn">
						<ul class="pagination pg-blue">

						{% if blogs.has_previous %}
							<!--Arrow left-->
							<li class="page-item ">
							<a class="page-link" href="?page={{blogs.previous_page_number}}" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
								<span class="sr-only">Previous</span>
							</a>
							</li>
						{% else %}
							<li class="page-item disabled"></li>
						{% endif %}

						{% for pages in blogs.paginator.page_range %}
							{% if blogs.number == pages %}
							<li class="page-item ">
								<a class="page-link" href="#">{{pages}}</a>
							</li>
							{% else %}
							<li class="page-item"><a class="page-link current" href="?page={{pages}}">{{pages}}</a></li>
							{% endif %}    
						{% endfor %}

						{% if blogs.has_next %}
							<li class="page-item">
							<a class="page-link" href="?page={{blogs.next_page_number}}" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
								<span class="sr-only">Next</span>
							</a>
							</li>
							{% else %}
							<li class="page-item disabled"></li>
						{% endif %}
						</ul>
					</nav>
					<!--Pagination-->
					{% endif %}
    </section>
    <!-- Blog Section End -->
{% endblock %}

app/templates/app/login.html
{% extends "app/base.html" %}

{% load static %}
{% block content %}

 

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Login</h2>
                        <div class="breadcrumb__option">
                            <a href="./index.html">Home</a>
                            <a>Login</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->
    <!-- Sign up Section Begin -->
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
        <form action="" method="post">
            {% csrf_token %}
            {% for fm in form %}
            <div class="form-group mb-3">
                {{ fm.label_tag }} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
            </div>
            {% endfor %}
            <br>
            <div class=" text-primary fw-bold"><small>
            <a href="{% url 'password_reset' %}">Forgot Password?</a></small></div><br>
            <input type="submit" value="Login" class="btn btn-primary">
            <div class=" text-primary text-center fw-bold" ><small>New Here?
            <a href="{% url 'app:signup' %}" class="text-danger">Create an Account</a></small></div>
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p class="alert alert-danger my-3">{{error}}</p>
                {% endfor %}
            {% endif %}
            <br><br>
        </form>
        </div>
    </div>

    <!-- Checkout Section End -->



    
{% endblock %}

app/templates/app/password_reset.html
{% extends "app/base.html" %}

{% load static %}

{% block content %}

  

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'app/img/breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Reset Password</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->
    <br><br>
    <br><br>
    <br><br>
    <!-- Sign up Section Begin -->
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
        <form action="" method="post">
            {% csrf_token %}
            {% for fm in form %}
            <div class="form-group mb-3">
                {{ fm.label_tag }} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
            </div>
            {% endfor %}
            <input type="submit" value="Submit" class="btn btn-primary">
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p class="alert alert-danger my-3">{{error}}</p>
                {% endfor %}
            {% endif %}
            <br><br>
            <br><br>
            <br><br>
        </form>
        </div>
    </div>

    <!-- Checkout Section End -->
{% endblock %}

app/templates/app/searched-category.html
{% extends "app/base.html" %}

{% load static %}
{% load mathfilters %}

{% block content %}

   

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'app/img/ban_lo.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2> Shop</h2>
                        <div class="breadcrumb__option">
                            <a href="./index.html">Home</a>
                            <span>Shop</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Product Section Begin -->
    <section class="product spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-5">
                    <div class="sidebar">
                        <div class="sidebar__item">
                            <h4>Categories</h4>
                            <ul>
                            <li><a href="{% url 'app:category' 'Farine_Semoul' %}">Semolina flour</a></li>
                            <li><a href="{% url 'app:category' 'Pates' %}">Pasta</a></li>
                            <li><a href="{% url 'app:category' 'Gateaux' %}">Cakes</a></li>
                            <li><a href="{% url 'app:category' 'Sucrerie' %}">Sugar factory</a></li>
                            <li><a href="{% url 'app:category' 'Graines' %}">Seeds</a></li>
                            <li><a href="{% url 'app:category' 'Laitiers' %}">dairymen</a></li>
                            <li><a href="{% url 'app:category' 'Boisson' %}">Beverage</a></li>
                            <li><a href="{% url 'app:category' 'Produit_Fait_Maison' %}">Homemade Product</a></li>
                            <li><a href="{% url 'app:category' 'Compliment_Alimentaire' %}">supplements</a></li>
                              </ul>
                        </div>
                      
                        <div class="sidebar__item">
                            <div class="latest-product__text">
                                <h4>Latest Products</h4>
                                <div class="latest-product__slider owl-carousel">
                                    {% for chunk in latest_N_Products %}

                                    <div class="latest-prdouct__slider__item">
                                        {% for item in chunk %}
                                            <a href="{% url 'app:shop' %}" class="latest-product__item">
                                                <div class="latest-product__item__pic">
                                                    <img src="{{ item.image }}" alt="">
                                                </div>
                                                <div class="latest-product__item__text">
                                                    <h6>{{ item.title }}</h6>
                                                    <span>{{ item.price }}dz</span>
                                                </div>
                                            </a>
                                        {% endfor %}
                                    </div>

                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9 col-md-7">
                    <div class="filter__item">
                        <div class="row">
                            <div class="col-lg-4 col-md-5">
                                <div class="filter__sort">
                                    <span>Sort By</span>
                                    <select>
                                        <option value="0">Default</option>
                                        <option value="0">Default</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4">
                                <div class="filter__found">
                                    <h6><span>{{ products.count }}</span> Products found</h6>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-3">
                                <div class="filter__option">
                                    <span class="icon_grid-2x2"></span>
                                    <span class="icon_ul"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {% for product in products %}
                        <div class="col-lg-4 col-md-6 col-sm-6">
                            <div class="product__item">
                                <div class="product__item__pic set-bg" data-setbg="{{ product.image1.url }}">
                                    <ul class="product__item__pic__hover">
                                       
                                        <li><a><i  value="Click"onclick="testdemo();" class="fa fa-shopping-cart update-cart" data-product="{{ product.id }}" data-action="add"></i></a></li>
                                    </ul>
                                </div>
                                <div class="product__item__text">
                                    <h6><a href="{% url 'shop:productinfo' product.id %}">{{ product.title }}</a></h6>
                                    <h5>{{ product.price }} dz</h5>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
<!--                    <div class="product__pagination">-->
<!--                        <a href="#">1</a>-->
<!--                        <a href="#">2</a>-->
<!--                        <a href="#">3</a>-->
<!--                        <a href="#"><i class="fa fa-long-arrow-right"></i></a>-->
<!--                    </div>-->
                </div>
            </div>
        </div>
    </section>
    <!-- Product Section End -->

{% endblock %}

app/templates/app/test.html
{% extends "app/base.html" %}

{% load static %}

{% block content %}
ttttttttttttttttttttttttttttttttttttttttttttttt
{% endblock content %}

app/templates/app/user_profile.html
{% extends "app/base.html" %}

{% load static %}

{% block content %}

    

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Profile Edit</h2>
                      
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->


    <!-- Sign up Section Begin -->
    <div class="row justify-content-center mt-5">
        <div class="col-md-4">
            <h3>Welcome {{user.last_name}}</h3><br>
            <div>
               <ul class="list-unstyled">
                <li class="d-grid"><a href="{% url 'app:userprofile' %}" class="btn btn-primary">Profile</a></li>
                <li class="d-grid"><a href="{% url 'shop:cart' %}" class="btn">Cart</a></li>
               
               </ul>
            </div>
        </div>
        <div class="col-md-5">
        <form action="" method="post">
            {% csrf_token %}
            {% for fm in form %}
            <div class="form-group mb-3">
                {{ fm.label_tag }} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
            </div>
            {% endfor %}
            <input type="submit" value="Update" class="btn btn-primary">
            <br>
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p class="alert alert-danger my-3">{{error}}</p>
                {% endfor %}
            {% endif %}
        </form>
        </div>
    </div>

    <!-- Checkout Section End -->
{% endblock %}